apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: back
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '5000'
spec:
  selector: 
    app: api
  type: NodePort  
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30003