apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: tp-microservices-api:latest
          ports:
            - containerPort: 5000