version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  api:   
    depends_on:
      - mongodb 
    build:
      context: ./API
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      
  app:
    build:
      context: ./FRONT
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:80

  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - sonarqube-net

  sonarscanner:
    image: sonarsource/sonar-scanner-cli
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000/
      - SONAR_TOKEN=sqa_26108818d4fd4bbb6975a5b5cb80da116c392dfa
      - SONAR_SCANNER_OPTS=-Dsonar.projectKey=zoo-app
    depends_on:
      - sonarqube
    volumes:
      - ./:/usr/src/api
    networks:
      - sonarqube-net

networks:
  sonarqube-net:

volumes:
  mongodb_data: